language: go

go:
  - 1.7.x
  - 1.8.x

services:
  - mysql

install:
  - go get -u github.com/Masterminds/glide
  - glide install

before_script:
  - mysql -e 'CREATE DATABASE dev_pmm;'

script:
  - tests/runner.sh

notifications:
  email:
    on_success: change
    on_failure: change
